# Generated by Django 4.2.5 on 2023-09-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0002_alter_chatbotresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='input_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='chatbotresponse',
            name='response_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
