# Generated by Django 4.2.5 on 2023-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_remove_chathistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='user_input',
            field=models.TextField(null=True),
        ),
    ]
