# Generated by Django 4.2.5 on 2023-09-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_alter_chathistory_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='input_text',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotresponse',
            name='response_text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
